import React from "react";
import Head from "next/head";
import { Box, Input, Text } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [text, setText] = React.useState("");
  const [suggestions, setSuggestions] = React.useState([]);
  const [isFocus, setIsFocus] = React.useState(false);

  const options = [
    { id: 1, text: "React" },
    { id: 2, text: "Ruby on Rails" },
    { id: 3, text: "JavaScript" },
    { id: 4, text: "TypeScript" },
    { id: 5, text: "Go" },
    { id: 6, text: "HTML" },
    { id: 7, text: "CSS" },
  ];

  const handleChange = (text) => {
    let matches = [];
    if (text.length > 0) {
      matches = options.filter((opt) => {
        const regex = new RegExp(`${text}`, "gi");
        return opt.text.match(regex);
      });
    }
    setSuggestions(matches);
    setText(text);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w="100%" mt="40px">
        <Input
          onFocus={() => setIsFocus(true)}
          type="text"
          value={text}
          onChange={(e) => handleChange(e.target.value)}
          placeholder="text..."
        />
        {isFocus && (
          <Box
            w="100%"
            h="100%"
            boxShadow="md"
            bg="white"
            mt="8px"
            borderRadius="lg"
          >
            {suggestions?.map((suggestion, i) => (
              <Text
                cursor="pointer"
                bg="white"
                _hover={{ bg: "gray.100" }}
                key={i}
                p="8px 8px"
                onClick={async () => {
                  await setText(suggestion.text);
                  await setIsFocus(false);
                }}
              >
                {suggestion.text}
              </Text>
            ))}
          </Box>
        )}
      </Box>
    </div>
  );
}
